config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources:contacts,only:[:new,:create] do
    collection do
      post:confirm
    end
  end

  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :conversations do
    resources :messages
  end

  resources :poems, only: [:index,:show]
  resources :herpoems, only: [:index,:show]
  resources :users, only: [:index,:show]
  resources :relationships, only: [:create, :destroy]

end

app/models/poem.rb
class Poem < ActiveResource::Base
  self.site = "https://limitless-plains-63135.herokuapp.com/"
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  def index
    @poems = Poem.all
  end

  def show
    @poem = Poem.find(params[:id])
  end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<h1>ポエム一覧</h1>
<section class="container">
  <div class="row">
    <div class="poem_setting col-md-8 col-md-offset-2 col-sm-10">
      <% @poems.each do |poem| %>
        <div class="row">
          <div class="col-xs-offset-2 col-xs-2 title"><%= poem.title %></div>
          <div class="col-xs-5 content dot"><%= poem.content %></div>
          <div class="col-xs-3"><%= link_to "SHOW", herpoem_path(poem.id), class:"btn btn-info btn-xs" %></div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/poems/show.html.erb
<h1>ポエム詳細</h1>
<scetion class="content">
  <div class="row">
    <div class="poem_setting col-md-8 col-md-offset-2 col-sm-10">
      <div class="row">
        <div class="col-md-offset-2 col-xs-4 col-md-2 lbl">タイトル：</div>
        <div class="col-xs-8 col-md-8 title"><%= @poem.title %></div>
      </div>
      <div class="row">
        <div class="col-md-offset-2 col-xs-4 col-md-2 lbl">内容：</div>
        <div class="col-xs-8 col-md-8 content"><%= @poem.content %></div>
      </div>
    </div>
    <div class="col-xs-12"><%= link_to "一覧へ戻る", poems_path %></div>
  </div>
</scetion>